#!/usr/bin/env php
<?php

use Al3x5\xBot\Config;

if (file_exists('vendor/autoload.php')) {
    require_once 'vendor/autoload.php';
}

// Config
if (file_exists('config.php')) {
    $cfg = require 'config.php';
}

use Al3x5\xBot\Bot;
use Al3x5\xBot\Commands\HookAboutCommand;
use Al3x5\xBot\Commands\HookDeleteCommand;
use Al3x5\xBot\Commands\HookInfoCommand;
use Al3x5\xBot\Commands\HookSetCommand;
use Al3x5\xBot\Commands\InstallCommand;
use Al3x5\xBot\Commands\MakeCommandCommand;
use Al3x5\xBot\Commands\RegisterCommand;
use Al3x5\xBot\Commands\TelegramCallbackCommand;
use Al3x5\xBot\Commands\TelegramCommandCommand;
use Al3x5\xBot\Commands\TelegramConversationCommand;
use Al3x5\xBot\Commands\TelegramHandlerCommand;
use Symfony\Component\Console\Application;

if (!empty($cfg)) {
    Config::init($cfg);
}

$app = new Application(Bot::NAME, 'v' . Bot::VERSION);

// ... register commands
$app->add(new InstallCommand());
$app->add(new RegisterCommand());
//webhook
$app->add(new HookSetCommand());
$app->add(new HookDeleteCommand());
$app->add(new HookInfoCommand());
$app->add(new HookAboutCommand());
//make
if (!strpos(__DIR__, 'vendor')) {
    $app->add(new MakeCommandCommand());
}
//telegram
$app->add(new TelegramCommandCommand());
$app->add(new TelegramCallbackCommand());
$app->add(new TelegramConversationCommand());
$app->add(new TelegramHandlerCommand());


if (
    !file_exists(InstallCommand::configFile()) &&
    !file_exists('artisan')
) {
    $app->setDefaultCommand('install');
}

$app->run();
