#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
} else {
    require_once __DIR__ . '/vendor/autoload.php';
}

use Al3x5\xBot\Bot;
use Al3x5\xBot\Commands\HookAboutCommand;
use Al3x5\xBot\Commands\HookDeleteCommand;
use Al3x5\xBot\Commands\HookInfoCommand;
use Al3x5\xBot\Commands\HookSetCommand;
use Al3x5\xBot\Commands\InstallCommand;
use Symfony\Component\Console\Application;

$app = new Application(Bot::NAME, 'v'.Bot::VERSION);

// ... register commands
$app->add(new InstallCommand());
//webhook
$app->add(new HookSetCommand());
$app->add(new HookDeleteCommand());
$app->add(new HookInfoCommand());
$app->add(new HookAboutCommand());
//make
$app->add(new InstallCommand());
$app->add(new InstallCommand());
$app->add(new InstallCommand());
$app->add(new InstallCommand());
$app->add(new InstallCommand());

if (!file_exists(InstallCommand::configFile())) {
    $app->setDefaultCommand('install');
}

$app->run();
