#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

use Al3x5\xBot\Cli\Commands\InstallCommand;
use Symfony\Component\Console\Application;

$app = new Application('xBot CLI Tools', 'v1.0.0');

// ... register commands
$app->add(new InstallCommand());
$app->run();